server:
  forward-headers-strategy: none
  servlet:
    context-path: /zip-downloader
  port: 8080
hostname: local

config:

  datasource:
    server: c-f9qo77lmedakhuj6ve0h.yandexcloud.net:6432
    ssl: true
    sslmode: verify-full
    database: data-control
    username: data-control_preprod
    password: data-control

  server:
    url: http://localhost:8080

  client:
    fias:
      url: http://fias.nalog.ru
      path: /WebServices/Public/GetLastDownloadFileInfo

spring:
  application:
    name: zip-downloader
  liquibase:
    enabled: true
    drop-first: false
    database-change-log-lock-table: DATABASECHANGELOGLOCK
    database-change-log-table: DATABASECHANGELOG
    change-log: classpath:/db/db.changelog-master.xml
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${config.datasource.server}/${config.datasource.database}?&ApplicationName=${hostname}&ssl=${config.datasource.ssl}&sslmode=${config.datasource.sslmode}
    username: ${config.datasource.username}
    password: ${config.datasource.password}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      max-lifetime: 2000
      validation-timeout: 10000

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tags-sorter: alpha
    version: 1.00.0.0-BETA
  writer-with-default-pretty-printer: true

logging:
  level:
    ru.globaltruck.downloader.fias.handler: info
    ru.globaltruck.downloader.fias.service: info